# Generated by Django 5.0.9 on 2025-03-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articlepage_author_alter_articlepage_body'),
        ('utils', '0002_remove_authorsnippet_image_membersnippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorSnippet',
        ),
    ]
